### ISSUE TITLE
Research Javascript/SCORM developer who can create a Tetris game in js and then convert it to SCORM format

### ISSUE THREAD

**Issue by guillaumefe** [opencovid19-fr/opencovid19-fr.github.io#13]
We are looking for a developer to:
- Create a Tetris javascript application (for example based on [this tutorial](https://codeincomplete.com/articles/javascript-tetris/))
- The application will have to be **in English** at the beginning, but should provide a technical means for internationalization (several languages may be necessary).
- Add levels to the game so that the user has to play **20 minutes at least**
- Convert the application to [SCORM format](https://scorm.com/scorm-explained/)

Once the game application has been put in SCORM format, it will then be integrated between two questionnaires, within a [Beedez application](www.beedeez.com) (which makes its software available to the project).

It will then be deployed in Europe in order to evaluate the efficacy to prevent the appearance of **post-traumatic stress disorder** in vulnerable persons, victims, or relatives of victims, of Covid disease19.

**Please leave a comment here. Thank you in advance for your participation.**

----------------------

Nous recherchons un développeur pour:
- Créer une application javascript Tétris (par exemple en se basant sur [ce tutorial](https://codeincomplete.com/articles/javascript-tetris/))
- L'application devra être **en anglais** dans un premier temps mais doit fournir un moyen technique pour l'internationalisation (plusieurs langues pourront être nécessaires)
- Ajouter des niveaux au jeu de manière à ce que l'utilisateur doive jouer **20 minutes au moins**
- Convertir l'application au format [SCORM](https://scorm.com/scorm-explained/)

Une fois mise au format SCORM, l'application de jeu sera ensuite intégrée entre deux questionnaires, au sein d'une application [Beedez](www.beedeez.com) (qui met son logiciel à disposition du projet).

Elle sera ensuite déployée en Europe afin de tenter de prévenir l'apparition du **syndrome de stress post-traumatique** chez les personnes vulnérables, victimes, ou proches de victimes, de la maladie Covid19.

**Pour vous proposez laissez un commentaire ici. Merci d'avance pour votre participation.**

**Comment by bsene** [comment]
Hi,
As a polyglot (despite I assume proficiency in Javascript), I'm interessed by the challenge.
You can find by contact mails on my profile of course

**Comment by guillaumefe** [comment]
Thank your for your answer @bsene :) Are you experienced with, or ready to dig in, SCORM format?

**Comment by guillaumefe** [comment]
> Hi,
> As a polyglot (despite I assume proficiency in Javascript), I'm interessed by the challenge.
> You can find by contact mails on my profile of course

I made a reply on slack
