### ISSUE TITLE
un lien sur le Forex sur le site du Covid ?

### ISSUE THREAD

**Issue by banalg** [opencovid19-fr/opencovid19-fr.github.io#27]
Bonjour,

J'obtiens cette phrase sur votre page d'accueil, dans le bloc Qui sommes nous : 

Data against Covid est une organisation informelle issue de la société civile avec des développeurs, des data scientist, des ingénieurs, des chefs de qu'est ce que le forex projets et talents de tous corps de

Normal qu'on parle de Forex ?

![Screenshot_20200728-095425_Chrome.jpg](https://user-images.githubusercontent.com/2079896/88636680-8a894300-d0b9-11ea-9378-3f9a0f527978.jpg)

**Comment by abdoulsn** [comment]
Bonjour, merci pour cette notification, je suis allé sur le site mais j'ai pas vu cette erreur. Peut-être elle à été corrigé entre temps. Peux-tu me le confirmer @banalg ?

**Comment by abdoulsn** [comment]
Feel free to re open.

**Comment by glefait** [comment]
Ca vaut le coup de ré-ouvrir parce que je trouve la même chose aujourd'hui, cf capture.
![Capture d’écran de 2020-10-12 15-05-52](https://user-images.githubusercontent.com/7490317/95782052-0187ae00-0c9d-11eb-8e12-186d6630e91e.png)

Le chargement de certaines ressources semble très suspect.

**Comment by glefait** [comment]
J'ai l'impression que le domaine opencovid19.fr est indépendant du site https://opencovid19-fr.github.io et c'est sur ce domaine qu'on trouve des liens et scripts "hasardeux".
Or on a bien dans la description du projet github : "About: Source pour le site web de l'initiative > http://opencovid19.fr/"

@banalg est-ce que tu te rappelles si tu avais été sur le site en .fr ?

Si c'est le cas, il faudrait supprimer les liens vers le site en .fr. Et si la personne qui a acheté le domaine est dans les parages, ta machine est trouée.

**Comment by banalg** [comment]
Oui j'étais allé sur http://opencovid19.fr/, et je reproduis encore le message du Forex.

**Comment by abdoulsn** [comment]
Hello, en effet http://opencovid19.fr/  a été bloqué par AFNIC depuis longtemps. @jdesboeufs avait bien sollicité OVH pour régler ce problème mais en vain. cf [la discussion sur slack ](https://dataagainstcovid-19.slack.com/archives/CV5H7LSET/p1589055211420600)
Du coup je pense mieux vaut le supprimer cas c'est suspicieux comme tu l'as dit reste au admin de l'Organisation de voir ce qu'il faut faire.
@tiphaine une idée??

**Comment by tiphaine** [comment]
Hello, effectivement je n'ai pas la main sur http://opencovid19.fr/. 

Mais on peut aussi choisir de supprimer https://opencovid19-fr.github.io pour ne pas laisser les sources (pour se faire, il faut simplement supprimer le repo correspondant).

**Comment by abdoulsn** [comment]
C'est chelou en tout cas. Meme le titre en bas de page le lien y est incrusté!

**Comment by glefait** [comment]
> Mais on peut aussi choisir de supprimer https://opencovid19-fr.github.io pour ne pas laisser les sources (pour se faire, il faut simplement supprimer le repo correspondant).

Sans aller jusqu'à supprimer ce repo, ça serait bien de supprimer le lien vers le site en .fr dans la description du repo.
Le propriétaire du repo peut le changer simplement en cliquant sur la petite roue en haut à droite.

![Capture d’écran de 2020-10-13 08-15-28](https://user-images.githubusercontent.com/7490317/95859230-49094b00-0d2c-11eb-8e6b-c73fa6efc94c.png)

**Comment by tiphaine** [comment]
C'est fait, merci.

**Comment by abdoulsn** [comment]
@tiphaine ça marche pas!
